### PR TITLE
Code refactoring, more Swift style, remove circle gradient, and remove unnecessary files

### PR DESCRIPTION
**Pull request by m4rr**
- I guess that brilliant circle gradient is hard to make with just one UIView. It's a subject of designers, so I propose to remove it.
- And also, the whole Xcode project is unnecessary here. I guess just one `SwiftyGradient.swift` is enough. So I propose to remove superfluous files.

### CODE REVIEW

**Comment by m4rr** [comment]
rename back to `isHorizontal`

**Comment by BilalReffas** [comment]
Thank you :)

**Comment by m4rr** [comment]
Great! Don't you mind if I create a CocoaPods podspec for SwiftyGradient?

**Comment by BilalReffas** [comment]
Yeah I will :)

**Pull request merged**
